spring:
  security:
    oauth2:
      client:
        registration:        
          github:
            clientId: f3b607e263d1c0f1253d
            clientSecret: f1e9551236b1a4567fe35ef837f13431a232aa9e